# Generated by Django 6.0.7 on 2026-09-10 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_hiring_team',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='HiringTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=200)),
                ('team_unique_id', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=200)),
                ('website_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hiring_team_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
