# Generated by Django 6.0.7 on 2026-09-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_is_hiring_team_hiringteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiringteam',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
