# Generated by Django 6.0.7 on 2026-09-17 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_hiringteam_email_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200)),
                ('interview_date', models.DateTimeField()),
                ('interview_type', models.CharField(default='Technical', max_length=50)),
                ('duration_minutes', models.IntegerField(default=45)),
                ('meeting_link', models.URLField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_interviews', to=settings.AUTH_USER_MODEL)),
                ('hiring_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_bookings', to='accounts.hiringteam')),
            ],
        ),
    ]
