# Generated by Django 6.1.1 on 2026-10-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interested_roles',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
